name: Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: sbp_d09fd57e397d3e418404861042e7d5dbeaaf6858
      SUPABASE_DB_PASSWORD: qefkat-4kIhvo-rifmin
      PROJECT_ID: othzeoejxhnztqxskftm

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
